version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "8000:80"  # Aqui expomos a porta 80 do container para a porta 8000 local
    networks:
      - laravel
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: topic_notify_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  db_data:
